---


'.test_common': &job_test_common
  script:
    - 'python3 -m pip install tox'
    - 'python3 -m tox'
    - 'python3 -m tox -e package'

'test py36':
  <<: *job_test_common
  image: 'python:3.6'
  variables:
    'TOXENV': 'py36'

'test py37':
  <<: *job_test_common
  image: 'python:3.7'
  variables:
    'TOXENV': 'py37'


... EOF
